### ISSUE TITLE
Create a questionaire for RF community

### ISSUE THREAD

**Issue by manykarim** [MarketSquare/robotframeworkguides#3]
Create a questionaire for RF community members, to investigate gaps in documentation and training needs.

That data can be used to come up with an initial list of topics

- [x] Create questionaire draft
- [x] Decide where to publish questionaire
- [x] Publish
- [x] Analyze results

**Comment by zastress** [comment]
Second draft created here: https://my.forms.app/form/627a0185b838185b93631641

**Comment by manykarim** [comment]
Results were presented on 29-Jun-2022 by Miikka.

Overall, no surprises in the responses.
The community wants examples.
And they want to be able to find information easily.
