### ISSUE TITLE
"Getting result statistics" example not working.

### ISSUE THREAD

**Issue by gohierf** [MarketSquare/robotframeworkguides#58]
Hello,

I just tried running the [first example](https://github.com/MarketSquare/robotframeworkguides/blob/4ffc105cd9e92e02a1fffabea93b62ca1306aa34/website/docs/parsing_results.md?plain=1#L70-L76) of [Getting result statistics](https://docs.robotframework.org/docs/parsing_results#getting-result-statistics):

```python
from robot.api import ExecutionResult
result = ExecutionResult('output.xml')
stats = result.statistics
print(f"Number of Failed Tests: {stats.failed}")
print(f"Total number of Tests: {stats.passed}")
```

And I get the following error:
`AttributeError: 'Statistics' object has no attribute 'failed'`

[It seems that the proper way](https://robot-framework.readthedocs.io/en/stable/autodoc/robot.result.html#robot.result.executionresult.Result.statistics) to get these statistics are through the `total` attribute:

```python
print(f"Total number of Failed Tests: {stats.total.failed}")
print(f"Total number of Passed Tests: {stats.total.passed}")
```

**Comment by manykarim** [comment]
You're absolutely right, thank you.
It has been fixed.
