### ISSUE TITLE
"I'm looking for RPA" is out of date and will turn away new users

### ISSUE THREAD

**Issue by burrk** [MarketSquare/robotframeworkguides#71]
https://docs.robotframework.org/docs/getting_started/rpa

The Robot Framework Guides still recommend using Robocorp RPA libraries, RCC, and the Automation Studio!  Now that Robocorp is no longer maintaining the `RPA.*` Robot libraries and the Automation Studio is dead, this need to be replaced with something usable for RPA beginners, or at the very least removed.

P.S. I still like the RPA libraries, and I know they are not all dead, so it may be worth still mentioning them... but not RCC nor the Automation Studio.

**Comment by burrk** [comment]
P.S. The first paragraph on the main web page points to this page - which is really not good...  https://robotframework.org/

**Comment by simonmeggle** [comment]
I agree to remove RPA libraries and Automation Studio.
But RCC is still alive and imho completely underrated (not to say misunderstood sometimes...). 
Nevertheless, `venv` is the way to go for 97% of all RF users. For more complex deployments and special deployments, RCC is great. 
For that reason, I would still keep it in the list of tools for environment creation.

**Comment by burrk** [comment]
I wouldn't remove the RPA libraries at least not as a suggestion - they are great, some are still maintained, and I use them.  They are just risky because of their uncertain maintenance future - although that is true for all open source projects to different degrees.

As the first link in the first paragraph on the main website this guide needs to really useful for people just looking to try out RF.  And even if it was not linked to in such a prestigious spot, it is important functionality needs a working help guide.

**Comment by simonmeggle** [comment]
Side note: yesterday I have released a docker-compose setup for rccremote with nginx and certificate support. 
With that rcc can fetch environment blueprints (Python, Nodejs, whatever) from a central host and create isolated environments in just a blink of an eye - without any internet connection.

https://github.com/elabit/rccremote-docker

(Just to give an example of rccs versatility and uniqueness)

**Comment by burrk** [comment]
There is already a PR "Reworked I am looking for RPA page" #44 that is failing the build (@emanlove) I think it really needs finishing.

B.T.W. this is response to this discussion in Slack from a new user:  https://robotframework.slack.com/archives/C3C28F9DF/p1731351243281209

**Comment by d-biehl** [comment]
@simonmeggle 

Just to mention it, `rcc` depends on a manufacturer, has built-in commands that communicate with the manufacturer's cloud, and most importantly, it is no longer open source. The source code has been removed, and the license is now proprietary, no longer an open-source license. I'm not sure whether one should reference commercial, non-open-source compatible tools on a page that is about an open-source project.

**Comment by burrk** [comment]
@simonmeggle, based on @d-biehl's comment - I think `rcc` depends heavily on [Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html) for installation tasks - Does it do what you need?

**Comment by manykarim** [comment]
RPA Page has been updated
https://github.com/MarketSquare/robotframeworkguides/pull/44 has been merged and small error has been fixed
https://docs.robotframework.org/docs/getting_started/rpa
